In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
#numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1 

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('int32'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Creating a dataframe with pandas from numpy array
import pandas as pd
df  = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
ar1 = pd.Series(a1)
ar1

0    1
1    2
2    3
dtype: int32

## 2. Creating Numpy Arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int32')

In [18]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeroes = np.zeros((2,3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10,size = (3,5))

In [24]:
random_array

array([[0, 1, 1, 6, 9],
       [9, 7, 2, 5, 5],
       [4, 2, 7, 5, 8]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
np.random.seed(seed = 7)
np.random.random((5,3))

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [28]:
np.random.rand(5,3)

array([[0.90959353, 0.21338535, 0.45212396],
       [0.93120602, 0.02489923, 0.60054892],
       [0.9501295 , 0.23030288, 0.54848992],
       [0.90912837, 0.13316945, 0.52341258],
       [0.75040986, 0.66901324, 0.46775286]])

In [29]:
# pseudo random numbers
np.random.seed(seed = 4)
random_array_2 = np.random.randint(10, size=(5,3))
random_array_2

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2]])

## 3. Viewing Arrays and Matrices

In [30]:
np.unique(random_array_2)

array([1, 2, 4, 5, 7, 8, 9])

In [31]:
a1 

array([1, 2, 3])

In [32]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [34]:
a1[0], a1.shape

(1, (3,))

In [35]:
a2[0], a2.shape

(array([1, 2, 3]), (2, 3))

In [36]:
a3[:2,:2,:2], a3.shape

(array([[[ 1,  2],
         [ 4,  5]],
 
        [[10, 11],
         [13, 14]]]),
 (2, 3, 3))

In [37]:
a4 = np.random.randint(10, size = (2,3,4,5))

In [38]:
a4, a4.ndim

(array([[[[6, 4, 3, 0, 7],
          [5, 5, 9, 6, 6],
          [8, 2, 5, 8, 1],
          [2, 7, 0, 8, 3]],
 
         [[1, 0, 3, 2, 3],
          [2, 9, 2, 1, 0],
          [1, 9, 9, 0, 7],
          [2, 6, 3, 7, 8]],
 
         [[2, 6, 7, 7, 9],
          [2, 7, 5, 3, 0],
          [5, 4, 3, 8, 9],
          [5, 8, 6, 7, 0]]],
 
 
        [[[4, 6, 8, 4, 8],
          [1, 9, 5, 4, 2],
          [3, 4, 7, 6, 6],
          [8, 0, 3, 5, 6]],
 
         [[1, 1, 6, 0, 8],
          [7, 5, 7, 6, 8],
          [4, 4, 0, 7, 2],
          [1, 8, 8, 1, 3]],
 
         [[1, 3, 6, 7, 4],
          [0, 7, 3, 7, 9],
          [6, 6, 9, 3, 2],
          [7, 6, 7, 9, 4]]]]),
 4)

In [39]:
a4[:][:][:][:]

array([[[[6, 4, 3, 0, 7],
         [5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3]],

        [[1, 0, 3, 2, 3],
         [2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8]],

        [[2, 6, 7, 7, 9],
         [2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0]]],


       [[[4, 6, 8, 4, 8],
         [1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6]],

        [[1, 1, 6, 0, 8],
         [7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3]],

        [[1, 3, 6, 7, 4],
         [0, 7, 3, 7, 9],
         [6, 6, 9, 3, 2],
         [7, 6, 7, 9, 4]]]])

In [40]:
a4[:,:,:,:3]

array([[[[6, 4, 3],
         [5, 5, 9],
         [8, 2, 5],
         [2, 7, 0]],

        [[1, 0, 3],
         [2, 9, 2],
         [1, 9, 9],
         [2, 6, 3]],

        [[2, 6, 7],
         [2, 7, 5],
         [5, 4, 3],
         [5, 8, 6]]],


       [[[4, 6, 8],
         [1, 9, 5],
         [3, 4, 7],
         [8, 0, 3]],

        [[1, 1, 6],
         [7, 5, 7],
         [4, 4, 0],
         [1, 8, 8]],

        [[1, 3, 6],
         [0, 7, 3],
         [6, 6, 9],
         [7, 6, 7]]]])

## 4. Manipulating and Comparing arrays

### Aritmetic 

In [41]:
a1

array([1, 2, 3])

In [42]:
ones = np.ones(3)
ones


array([1., 1., 1.])

In [43]:
a1 + ones

array([2., 3., 4.])

In [44]:
a1 - ones

array([0., 1., 2.])

In [45]:
a1 * ones

array([1., 2., 3.])

In [46]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [48]:
a1

array([1, 2, 3])

In [49]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [51]:
# How can we reshape a2 to be compatible with a3
# a2 * a3, 
a2.shape, a3.shape

((2, 3), (2, 3, 3))

In [52]:
a1 / ones

array([1., 2., 3.])

In [53]:
a2 / a1

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [54]:
a2 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [55]:
np.square(a2)

array([[ 1,  4,  9],
       [16, 25, 36]])

### Aggregation

In [56]:
a1

array([1, 2, 3])

In [57]:
sum(a1)

6

In [58]:
np.sum(a1)

6

In [59]:
#  Create a massive Numpy array
massive_array = np.random.random(100000)

In [60]:
massive_array[:10]

array([0.41903403, 0.90242186, 0.97961626, 0.62356884, 0.08318412,
       0.73299872, 0.6786854 , 0.82602287, 0.34745134, 0.05888009])

In [61]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

9.32 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
32.9 µs ± 149 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [62]:
# standard deviation
np.std(a2)

1.707825127659933

In [63]:
# variance
np.var(a2)

2.9166666666666665

In [64]:
np.sqrt(np.var(a2))

1.707825127659933

## Rehsaping and Transposing

In [65]:
a2 , a2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [66]:
a3 , a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [67]:
a2 = a2.reshape((2,3,1))

In [68]:
a2 * a3

array([[[  1,   2,   3],
        [  8,  10,  12],
        [ 21,  24,  27]],

       [[ 40,  44,  48],
        [ 65,  70,  75],
        [ 96, 102, 108]]])

In [69]:
(a2 * a3).T

array([[[  1,  40],
        [  8,  65],
        [ 21,  96]],

       [[  2,  44],
        [ 10,  70],
        [ 24, 102]],

       [[  3,  48],
        [ 12,  75],
        [ 27, 108]]])

## Dot Product

In [70]:
np.random.seed(0)

mat1 = np.random.randint(10,size=(5,3)),
mat2 = np.random.randint(10,size=(5,3))

In [73]:
# mat1.shape, mat2.shape

In [72]:
# ElementWise 
mat1 * mat2

array([[[30,  0, 21],
        [24,  7, 45],
        [27, 40, 18],
        [16, 21,  0],
        [24, 40,  0]]])

In [74]:
np.dot(mat1,mat2)

ValueError: shapes (1,5,3) and (5,3) not aligned: 3 (dim 2) != 5 (dim 0)

In [75]:
mat1 = np.transpose(mat1)

In [76]:
np.dot(mat1,mat2)

ValueError: shapes (3,5,1) and (5,3) not aligned: 1 (dim 2) != 5 (dim 0)

## Dot Prodcut example

In [78]:
np.random.seed(0)
sale_amount = np.random.randint(20, size=(5,3))
sale_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [79]:
weekly_sales = pd.DataFrame(sale_amount, index=['Mon','Tue','Wed','Thurs','Fri'],
                           columns = ['Almond Butter','Peanut butter','Cashew butter'])
weekly_sales

Almond Butter  Peanut butter  Cashew butter
Mon               12             15              0
Tue                3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [80]:
prices_array = np.array([10,8,12])
prices_array

array([10,  8, 12])

In [81]:
butter_prices = pd.DataFrame(prices_array.reshape(1,3), index = ['Price'],
                            columns = ['Almond Butter','Peanut butter','Cashew butter'])

In [82]:
butter_prices

Almond Butter  Peanut butter  Cashew butter
Price             10              8             12

In [83]:
total = sale_amount.dot(prices_array.T)

In [84]:
total

array([240, 138, 458, 232, 142])

In [ ]:
butter_prices, butter_prices.shape

In [ ]:
weekly_sales, weekly_sales.shape

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [ ]:
daily_sales

In [ ]:
weekly_sales['Total'] = daily_sales.T

In [ ]:
weekly_sales

### Comparison Operator

In [ ]:
a2,a1

In [ ]:
a1 > a2

In [ ]:
np.random.seed(0)
random_array = np.random.randint(10,size=(5,3))
random_array

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array.T)

## 6. Practical example

In [90]:
from matplotlib.image import imread

In [93]:
panda = imread("panda.png")
type(panda)

numpy.ndarray

In [94]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [95]:
panda.size

24465000

In [96]:
panda.shape

(2330, 3500, 3)

In [97]:
panda.ndim

3

In [99]:
car = imread("car-photo.png")
car.size,car.shape,car.ndim

(991300, (431, 575, 4), 3)

In [100]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [101]:
dog = imread("dog-photo.png")

In [102]:
dog

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

<img src="panda.png"/>